/*
 * FIN Financial Management System
 * 
 * Copyright (c) 2024-2025 Sthwalo Holdings (Pty) Ltd.
 * Owner: Immaculate Nyoni
 * Contact: sthwaloe@gmail.com | +27 61 514 6185
 * 
 * This source code is licensed under the Apache License 2.0.
 * Commercial use of the APPLICATION requires separate licensing.
 * 
 * Contains proprietary algorithms and business logic.
 * Unauthorized commercial use is strictly prohibited.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package fin.service;

import com.itextpdf.text.*;
import fin.license.LicenseManager;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Centralized service for PDF branding, footers, and copyright information.
 * Ensures all PDFs generated by the system have consistent branding and legal protection.
 * 
 * This service integrates with LicenseManager to include proper copyright notices
 * and license information in all generated documents.
 */
public class PdfBrandingService {
    
    // Standard fonts for PDF branding
    private static final Font FOOTER_FONT = new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.GRAY);
    private static final Font COPYRIGHT_FONT = new Font(Font.FontFamily.HELVETICA, 7, Font.NORMAL, BaseColor.LIGHT_GRAY);
    
    // Branding constants
    private static final String SYSTEM_NAME = "FIN Financial Management System";
    private static final String COPYRIGHT_HOLDER = "Immaculate Nyoni";
    private static final String COMPANY_NAME = "Sthwalo Holdings (Pty) Ltd";
    private static final String CONTACT_EMAIL = "sthwaloe@gmail.com";
    private static final String CONTACT_PHONE = "+27 61 514 6185";
    
    /**
     * Adds a standard footer to the PDF document with system branding and timestamp.
     * This footer appears at the bottom of every page.
     * 
     * @param document The PDF document to add the footer to
     * @param pageNumber The current page number (1-based)
     * @throws DocumentException if there's an error adding the footer
     */
    public void addStandardFooter(Document document, int pageNumber) throws DocumentException {
        Paragraph footer = new Paragraph();
        footer.setFont(FOOTER_FONT);
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(20);
        
        // System name and page number
        footer.add("Generated using " + SYSTEM_NAME + " | ");
        footer.add("Page " + pageNumber + " | ");
        
        // Timestamp
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        footer.add("Generated: " + now.format(formatter));
        
        document.add(footer);
    }
    
    /**
     * Adds a comprehensive copyright notice to the PDF document.
     * This includes copyright holder, company information, and license details.
     * 
     * @param document The PDF document to add the copyright to
     * @throws DocumentException if there's an error adding the copyright notice
     */
    public void addCopyrightNotice(Document document) throws DocumentException {
        Paragraph copyright = new Paragraph();
        copyright.setFont(COPYRIGHT_FONT);
        copyright.setAlignment(Element.ALIGN_CENTER);
        copyright.setSpacingBefore(10);
        
        copyright.add("Copyright © 2025 " + COPYRIGHT_HOLDER + " / " + COMPANY_NAME + "\n");
        copyright.add("Contact: " + CONTACT_EMAIL + " | " + CONTACT_PHONE + "\n");
        copyright.add("Licensed under Apache License 2.0 | Proprietary algorithms and business logic\n");
        copyright.add("Unauthorized commercial use is strictly prohibited");
        
        document.add(copyright);
    }
    
    /**
     * Adds both standard footer and copyright notice to the document.
     * This is the recommended method for most PDF generation use cases.
     * 
     * @param document The PDF document to add branding to
     * @param pageNumber The current page number (1-based)
     * @throws DocumentException if there's an error adding the branding
     */
    public void addFullBranding(Document document, int pageNumber) throws DocumentException {
        addStandardFooter(document, pageNumber);
        addCopyrightNotice(document);
    }
    
    /**
     * Gets the copyright text as a plain string for use in other contexts.
     * 
     * @return Copyright text including holder, company, and year
     */
    public String getCopyrightText() {
        return "Copyright © 2025 " + COPYRIGHT_HOLDER + " / " + COMPANY_NAME;
    }
    
    /**
     * Gets the full license information as a string.
     * 
     * @return Complete license and contact information
     */
    public String getLicenseInfo() {
        return getCopyrightText() + "\n" +
               "Contact: " + CONTACT_EMAIL + " | " + CONTACT_PHONE + "\n" +
               "Licensed under Apache License 2.0\n" +
               "Commercial use requires separate licensing";
    }
    
    /**
     * Gets the system name for branding purposes.
     * 
     * @return The system name
     */
    public String getSystemName() {
        return SYSTEM_NAME;
    }
    
    /**
     * Gets the copyright holder name.
     * 
     * @return The copyright holder
     */
    public String getCopyrightHolder() {
        return COPYRIGHT_HOLDER;
    }
    
    /**
     * Gets the company name.
     * 
     * @return The company name
     */
    public String getCompanyName() {
        return COMPANY_NAME;
    }
    
    /**
     * Checks if the current license allows commercial use.
     * Delegates to LicenseManager for actual license checking.
     * 
     * @return true if commercial use is allowed, false otherwise
     */
    public boolean isCommercialUseAllowed() {
        return LicenseManager.checkLicenseCompliance();
    }
    
    /**
     * Creates a watermark for non-commercial use documents.
     * This can be used to mark documents generated under personal use license.
     * 
     * @return Watermark text for personal use
     */
    public String getPersonalUseWatermark() {
        return "PERSONAL USE ONLY - NOT FOR COMMERCIAL DISTRIBUTION";
    }
}
