-- V10__Populate_Chart_Of_Accounts_Templates.sql
-- Populate chart of accounts templates with IFRS-compliant structures
-- Only populate industries that don't already have templates

-- Water Supply; Sewerage, Waste Management (36-39)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(5, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(5, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(5, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Infrastructure assets'),
(5, '1111', 'Water Treatment Plants', NULL, 4, true, 'Treatment facilities'),
(5, '1112', 'Pumping Stations', NULL, 4, false, 'Water pumps and stations'),
(5, '1113', 'Pipe Networks', NULL, 4, false, 'Water distribution pipes'),
(5, '1114', 'Vehicles', NULL, 4, false, 'Service vehicles'),
(5, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(5, '1210', 'Inventories', NULL, 3, true, 'Chemicals, spare parts'),
(5, '1220', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(5, '1230', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(5, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(5, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(5, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(5, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(5, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(5, '2210', 'Loans and Borrowings', NULL, 3, true, 'Infrastructure financing'),
(5, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(5, '2310', 'Trade Payables', NULL, 3, true, 'Chemical and service suppliers'),
(5, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(5, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(5, '3100', 'REVENUE', NULL, 2, true, 'Water and waste services'),
(5, '3110', 'Water Sales', NULL, 3, true, 'Water supply revenue'),
(5, '3120', 'Waste Management', NULL, 3, true, 'Sewerage and waste services'),
(5, '3130', 'Other Services', NULL, 3, false, 'Consulting, maintenance'),
(5, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(5, '4100', 'COST OF SALES', NULL, 2, true, 'Service delivery costs'),
(5, '4110', 'Chemicals and Treatment', NULL, 3, true, 'Water treatment chemicals'),
(5, '4120', 'Energy Costs', NULL, 3, true, 'Electricity for pumping'),
(5, '4130', 'Maintenance', NULL, 3, true, 'Infrastructure maintenance'),
(5, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(5, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(5, '4220', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(5, '4230', 'Insurance', NULL, 3, true, 'Infrastructure insurance'),
(5, '4240', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 5);

-- Construction (41-43)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(6, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(6, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(6, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Construction equipment'),
(6, '1111', 'Heavy Machinery', NULL, 4, true, 'Excavators, bulldozers'),
(6, '1112', 'Vehicles', NULL, 4, false, 'Transport vehicles'),
(6, '1113', 'Tools and Equipment', NULL, 4, false, 'Construction tools'),
(6, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(6, '1210', 'Construction in Progress', NULL, 3, true, 'Work in progress'),
(6, '1220', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(6, '1230', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(6, '1240', 'Retentions Receivable', NULL, 3, false, 'Contract retentions'),
(6, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(6, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(6, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(6, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(6, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(6, '2210', 'Loans and Borrowings', NULL, 3, true, 'Construction financing'),
(6, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(6, '2310', 'Trade Payables', NULL, 3, true, 'Material and subcontractor payables'),
(6, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(6, '2330', 'Progress Payments', NULL, 3, false, 'Customer progress payments'),
(6, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(6, '3100', 'REVENUE', NULL, 2, true, 'Construction revenue'),
(6, '3110', 'Contract Revenue', NULL, 3, true, 'Construction contract income'),
(6, '3120', 'Variation Orders', NULL, 3, false, 'Contract variations'),
(6, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(6, '4100', 'COST OF SALES', NULL, 2, true, 'Direct construction costs'),
(6, '4110', 'Materials', NULL, 3, true, 'Building materials'),
(6, '4120', 'Subcontractors', NULL, 3, true, 'Subcontractor costs'),
(6, '4130', 'Labor', NULL, 3, true, 'Construction labor'),
(6, '4140', 'Equipment Rental', NULL, 3, true, 'Heavy equipment rental'),
(6, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(6, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(6, '4220', 'Depreciation', NULL, 3, true, 'Equipment depreciation'),
(6, '4230', 'Insurance', NULL, 3, true, 'Construction insurance'),
(6, '4240', 'Marketing', NULL, 3, true, 'Business development'),
(6, '4250', 'Office Expenses', NULL, 3, true, 'Administrative costs'),
(6, '4260', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 6);

-- Wholesale and Retail Trade (45-47)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(7, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(7, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(7, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Store fixtures, vehicles'),
(7, '1111', 'Store Fixtures', NULL, 4, true, 'Shelving, displays'),
(7, '1112', 'Vehicles', NULL, 4, false, 'Delivery vehicles'),
(7, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(7, '1210', 'Inventories', NULL, 3, true, 'Goods for sale'),
(7, '1220', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(7, '1230', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(7, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(7, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(7, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(7, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(7, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(7, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(7, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(7, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(7, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(7, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(7, '3100', 'REVENUE', NULL, 2, true, 'Sales revenue'),
(7, '3110', 'Product Sales', NULL, 3, true, 'Goods sales'),
(7, '3120', 'Service Revenue', NULL, 3, false, 'Additional services'),
(7, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(7, '4100', 'COST OF SALES', NULL, 2, true, 'Cost of goods sold'),
(7, '4110', 'Purchases', NULL, 3, true, 'Goods purchased'),
(7, '4120', 'Freight In', NULL, 3, true, 'Shipping costs'),
(7, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(7, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(7, '4220', 'Rent', NULL, 3, true, 'Store rent'),
(7, '4230', 'Utilities', NULL, 3, true, 'Electricity, water'),
(7, '4240', 'Marketing', NULL, 3, true, 'Advertising, promotions'),
(7, '4250', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(7, '4260', 'Insurance', NULL, 3, true, 'Business insurance'),
(7, '4270', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 7);

-- Transportation and Storage (49-53)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(8, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(8, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(8, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Vehicles, equipment'),
(8, '1111', 'Vehicles', NULL, 4, true, 'Trucks, cars'),
(8, '1112', 'Equipment', NULL, 4, false, 'Loading equipment'),
(8, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(8, '1210', 'Inventories', NULL, 3, true, 'Fuel, supplies'),
(8, '1220', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(8, '1230', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(8, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(8, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(8, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(8, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(8, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(8, '2210', 'Loans and Borrowings', NULL, 3, true, 'Vehicle financing'),
(8, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(8, '2310', 'Trade Payables', NULL, 3, true, 'Fuel and service suppliers'),
(8, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(8, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(8, '3100', 'REVENUE', NULL, 2, true, 'Transportation revenue'),
(8, '3110', 'Freight Revenue', NULL, 3, true, 'Shipping income'),
(8, '3120', 'Storage Revenue', NULL, 3, false, 'Warehouse income'),
(8, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(8, '4100', 'COST OF SALES', NULL, 2, true, 'Direct transportation costs'),
(8, '4110', 'Fuel', NULL, 3, true, 'Vehicle fuel'),
(8, '4120', 'Vehicle Maintenance', NULL, 3, true, 'Repairs and servicing'),
(8, '4130', 'Tolls', NULL, 3, true, 'Road tolls'),
(8, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(8, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(8, '4220', 'Depreciation', NULL, 3, true, 'Vehicle depreciation'),
(8, '4230', 'Insurance', NULL, 3, true, 'Vehicle insurance'),
(8, '4240', 'Licenses', NULL, 3, true, 'Operating licenses'),
(8, '4250', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 8);

-- Accommodation and Food Service Activities (55-56)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(9, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(9, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(9, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Hotel/restaurant equipment'),
(9, '1111', 'Buildings', NULL, 4, true, 'Hotel/restaurant buildings'),
(9, '1112', 'Furniture and Fixtures', NULL, 4, true, 'Hotel furniture'),
(9, '1113', 'Kitchen Equipment', NULL, 4, true, 'Cooking equipment'),
(9, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(9, '1210', 'Inventories', NULL, 3, true, 'Food and beverages'),
(9, '1220', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(9, '1230', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(9, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(9, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(9, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(9, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(9, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(9, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(9, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(9, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(9, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(9, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(9, '3100', 'REVENUE', NULL, 2, true, 'Hospitality revenue'),
(9, '3110', 'Room Revenue', NULL, 3, true, 'Hotel room sales'),
(9, '3120', 'Food and Beverage', NULL, 3, true, 'Restaurant sales'),
(9, '3130', 'Other Services', NULL, 3, false, 'Conferences, events'),
(9, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(9, '4100', 'COST OF SALES', NULL, 2, true, 'Cost of goods sold'),
(9, '4110', 'Food and Beverage Costs', NULL, 3, true, 'Ingredients, beverages'),
(9, '4120', 'Room Costs', NULL, 3, true, 'Room maintenance'),
(9, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(9, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(9, '4220', 'Utilities', NULL, 3, true, 'Electricity, water, gas'),
(9, '4230', 'Marketing', NULL, 3, true, 'Advertising, promotions'),
(9, '4240', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(9, '4250', 'Insurance', NULL, 3, true, 'Business insurance'),
(9, '4260', 'Cleaning', NULL, 3, true, 'Housekeeping costs'),
(9, '4270', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 9);

-- Information and Communication (58-63)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(10, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(10, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(10, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'IT equipment, software'),
(10, '1111', 'Computers and Servers', NULL, 4, true, 'Hardware assets'),
(10, '1112', 'Software', NULL, 4, true, 'Software licenses'),
(10, '1113', 'Network Equipment', NULL, 4, false, 'Routers, switches'),
(10, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(10, '1210', 'Trade Receivables', NULL, 3, true, 'Customer receivables'),
(10, '1220', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(10, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(10, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(10, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(10, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(10, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(10, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(10, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(10, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(10, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(10, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(10, '3100', 'REVENUE', NULL, 2, true, 'Service revenue'),
(10, '3110', 'Service Fees', NULL, 3, true, 'Consulting, development fees'),
(10, '3120', 'Software Sales', NULL, 3, false, 'Product sales'),
(10, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(10, '4100', 'COST OF SALES', NULL, 2, true, 'Direct service costs'),
(10, '4110', 'Subcontractors', NULL, 3, true, 'Third-party services'),
(10, '4120', 'Software Licenses', NULL, 3, true, 'Third-party software'),
(10, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(10, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(10, '4220', 'Office Rent', NULL, 3, true, 'Workspace costs'),
(10, '4230', 'Utilities', NULL, 3, true, 'Electricity, internet'),
(10, '4240', 'Marketing', NULL, 3, true, 'Business development'),
(10, '4250', 'Depreciation', NULL, 3, true, 'Equipment depreciation'),
(10, '4260', 'Insurance', NULL, 3, true, 'Professional liability'),
(10, '4270', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 10);

-- Financial and Insurance Activities (64-66)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(11, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(11, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(11, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Office equipment'),
(11, '1111', 'Computers', NULL, 4, true, 'Workstations'),
(11, '1112', 'Furniture', NULL, 4, false, 'Office furniture'),
(11, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(11, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(11, '1220', 'Loans Receivable', NULL, 3, true, 'Outstanding loans'),
(11, '1230', 'Investment Securities', NULL, 3, true, 'Financial instruments'),
(11, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(11, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(11, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(11, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(11, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(11, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(11, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(11, '2310', 'Deposits', NULL, 3, true, 'Customer deposits'),
(11, '2320', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(11, '2330', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(11, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(11, '3100', 'REVENUE', NULL, 2, true, 'Financial revenue'),
(11, '3110', 'Interest Income', NULL, 3, true, 'Loan interest'),
(11, '3120', 'Fee Income', NULL, 3, true, 'Service fees'),
(11, '3130', 'Investment Income', NULL, 3, false, 'Portfolio returns'),
(11, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(11, '4100', 'COST OF SALES', NULL, 2, true, 'Direct financial costs'),
(11, '4110', 'Interest Expense', NULL, 3, true, 'Borrowing costs'),
(11, '4120', 'Bad Debts', NULL, 3, true, 'Loan losses'),
(11, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(11, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(11, '4220', 'Office Expenses', NULL, 3, true, 'Administrative costs'),
(11, '4230', 'Marketing', NULL, 3, true, 'Client acquisition'),
(11, '4240', 'Depreciation', NULL, 3, true, 'Equipment depreciation'),
(11, '4250', 'Insurance', NULL, 3, true, 'Professional indemnity'),
(11, '4260', 'Regulatory Fees', NULL, 3, true, 'Compliance costs'),
(11, '4270', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 11);

-- Real Estate Activities (68)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(12, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(12, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(12, '1110', 'Investment Properties', NULL, 3, true, 'Rental properties'),
(12, '1111', 'Residential Properties', NULL, 4, true, 'Houses, apartments'),
(12, '1112', 'Commercial Properties', NULL, 4, false, 'Office buildings'),
(12, '1120', 'Property, Plant and Equipment', NULL, 3, true, 'Office equipment'),
(12, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(12, '1210', 'Trade Receivables', NULL, 3, true, 'Tenant receivables'),
(12, '1220', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(12, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(12, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(12, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(12, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(12, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(12, '2210', 'Mortgages', NULL, 3, true, 'Property financing'),
(12, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(12, '2310', 'Trade Payables', NULL, 3, true, 'Property management suppliers'),
(12, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(12, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(12, '3100', 'REVENUE', NULL, 2, true, 'Rental income'),
(12, '3110', 'Rental Income', NULL, 3, true, 'Property rentals'),
(12, '3120', 'Property Sales', NULL, 3, false, 'Property disposals'),
(12, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(12, '4100', 'COST OF SALES', NULL, 2, true, 'Property holding costs'),
(12, '4110', 'Property Taxes', NULL, 3, true, 'Rates and taxes'),
(12, '4120', 'Maintenance', NULL, 3, true, 'Repairs and maintenance'),
(12, '4130', 'Insurance', NULL, 3, true, 'Property insurance'),
(12, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(12, '4210', 'Employee Costs', NULL, 3, true, 'Property management salaries'),
(12, '4220', 'Depreciation', NULL, 3, true, 'Property depreciation'),
(12, '4230', 'Marketing', NULL, 3, true, 'Property marketing'),
(12, '4240', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 12);

-- Professional, Scientific and Technical Activities (69-75)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(14, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(14, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(14, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Office equipment'),
(14, '1111', 'Computers', NULL, 4, true, 'Workstations'),
(14, '1112', 'Software', NULL, 4, true, 'Professional software'),
(14, '1113', 'Furniture', NULL, 4, false, 'Office furniture'),
(14, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(14, '1210', 'Trade Receivables', NULL, 3, true, 'Client receivables'),
(14, '1220', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(14, '1230', 'Work in Progress', NULL, 3, false, 'Unbilled services'),
(14, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(14, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(14, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(14, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(14, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(14, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(14, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(14, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(14, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(14, '2330', 'Client Retainers', NULL, 3, false, 'Advance payments'),
(14, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(14, '3100', 'REVENUE', NULL, 2, true, 'Professional services'),
(14, '3110', 'Professional Fees', NULL, 3, true, 'Consulting, legal fees'),
(14, '3120', 'Project Revenue', NULL, 3, false, 'Project-based income'),
(14, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(14, '4100', 'COST OF SALES', NULL, 2, true, 'Direct service costs'),
(14, '4110', 'Subcontractors', NULL, 3, true, 'Third-party professionals'),
(14, '4120', 'Travel', NULL, 3, true, 'Client visits'),
(14, '4130', 'Research', NULL, 3, true, 'Professional development'),
(14, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(14, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(14, '4220', 'Office Rent', NULL, 3, true, 'Workspace costs'),
(14, '4230', 'Utilities', NULL, 3, true, 'Electricity, internet'),
(14, '4240', 'Marketing', NULL, 3, true, 'Business development'),
(14, '4250', 'Depreciation', NULL, 3, true, 'Equipment depreciation'),
(14, '4260', 'Insurance', NULL, 3, true, 'Professional indemnity'),
(14, '4270', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 14);

-- Administrative and Support Service Activities (77-82)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(15, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(15, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(15, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Office equipment'),
(15, '1111', 'Computers', NULL, 4, true, 'Workstations'),
(15, '1112', 'Furniture', NULL, 4, false, 'Office furniture'),
(15, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(15, '1210', 'Trade Receivables', NULL, 3, true, 'Client receivables'),
(15, '1220', 'Cash and Cash Equivalents', NULL, 3, true, 'Bank accounts'),
(15, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(15, '2100', 'EQUITY', NULL, 2, true, 'Owner''s equity'),
(15, '2110', 'Share Capital', NULL, 3, true, 'Initial capital'),
(15, '2120', 'Retained Earnings', NULL, 3, true, 'Accumulated profits'),
(15, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(15, '2210', 'Loans and Borrowings', NULL, 3, true, 'Business financing'),
(15, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(15, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(15, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(15, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(15, '3100', 'REVENUE', NULL, 2, true, 'Service revenue'),
(15, '3110', 'Service Fees', NULL, 3, true, 'Administrative services'),
(15, '3120', 'Consulting', NULL, 3, false, 'Management consulting'),
(15, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(15, '4100', 'COST OF SALES', NULL, 2, true, 'Direct service costs'),
(15, '4110', 'Subcontractors', NULL, 3, true, 'Third-party services'),
(15, '4120', 'Travel', NULL, 3, true, 'Client visits'),
(15, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(15, '4210', 'Employee Costs', NULL, 3, true, 'Salaries and benefits'),
(15, '4220', 'Office Rent', NULL, 3, true, 'Workspace costs'),
(15, '4230', 'Utilities', NULL, 3, true, 'Electricity, internet'),
(15, '4240', 'Marketing', NULL, 3, true, 'Business development'),
(15, '4250', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 15);

-- Public Administration and Defence (84)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(17, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(17, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(17, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Government assets'),
(17, '1111', 'Buildings', NULL, 4, true, 'Office buildings'),
(17, '1112', 'Vehicles', NULL, 4, true, 'Fleet vehicles'),
(17, '1113', 'Equipment', NULL, 4, false, 'Specialized equipment'),
(17, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(17, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'Government funds'),
(17, '1220', 'Receivables', NULL, 3, true, 'Tax receivables'),
(17, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(17, '2100', 'EQUITY', NULL, 2, true, 'Government equity'),
(17, '2110', 'Capital', NULL, 3, true, 'Government funding'),
(17, '2120', 'Reserves', NULL, 3, true, 'Accumulated reserves'),
(17, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(17, '2210', 'Government Loans', NULL, 3, true, 'Intergovernmental loans'),
(17, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(17, '2310', 'Payables', NULL, 3, true, 'Supplier accounts'),
(17, '2320', 'Tax Liabilities', NULL, 3, true, 'Outstanding payments'),
(17, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(17, '3100', 'REVENUE', NULL, 2, true, 'Government revenue'),
(17, '3110', 'Tax Revenue', NULL, 3, true, 'Tax collections'),
(17, '3120', 'Grants', NULL, 3, true, 'Government grants'),
(17, '3130', 'Fees', NULL, 3, false, 'Service fees'),
(17, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(17, '4100', 'COST OF SALES', NULL, 2, true, 'Service delivery costs'),
(17, '4110', 'Program Costs', NULL, 3, true, 'Government programs'),
(17, '4120', 'Infrastructure', NULL, 3, true, 'Public infrastructure'),
(17, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(17, '4210', 'Employee Costs', NULL, 3, true, 'Civil service salaries'),
(17, '4220', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(17, '4230', 'Maintenance', NULL, 3, true, 'Facility maintenance'),
(17, '4240', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 17);

-- Education (85)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(18, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(18, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(18, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Educational facilities'),
(18, '1111', 'Buildings', NULL, 4, true, 'School buildings'),
(18, '1112', 'Furniture', NULL, 4, true, 'Classroom furniture'),
(18, '1113', 'Equipment', NULL, 4, true, 'Teaching equipment'),
(18, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(18, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'School funds'),
(18, '1220', 'Student Receivables', NULL, 3, true, 'Tuition receivables'),
(18, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(18, '2100', 'EQUITY', NULL, 2, true, 'Institution equity'),
(18, '2110', 'Capital', NULL, 3, true, 'Initial funding'),
(18, '2120', 'Reserves', NULL, 3, true, 'Accumulated reserves'),
(18, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(18, '2210', 'Loans and Borrowings', NULL, 3, true, 'Educational financing'),
(18, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(18, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(18, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(18, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(18, '3100', 'REVENUE', NULL, 2, true, 'Educational revenue'),
(18, '3110', 'Tuition Fees', NULL, 3, true, 'Student fees'),
(18, '3120', 'Government Grants', NULL, 3, true, 'Educational funding'),
(18, '3130', 'Other Income', NULL, 3, false, 'Donations, events'),
(18, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(18, '4100', 'COST OF SALES', NULL, 2, true, 'Educational delivery costs'),
(18, '4110', 'Teaching Materials', NULL, 3, true, 'Books, supplies'),
(18, '4120', 'Facility Costs', NULL, 3, true, 'Maintenance, utilities'),
(18, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(18, '4210', 'Employee Costs', NULL, 3, true, 'Teacher and staff salaries'),
(18, '4220', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(18, '4230', 'Insurance', NULL, 3, true, 'Facility insurance'),
(18, '4240', 'Marketing', NULL, 3, true, 'Student recruitment'),
(18, '4250', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 18);

-- Human Health and Social Work Activities (86-88)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(19, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(19, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(19, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Medical facilities'),
(19, '1111', 'Buildings', NULL, 4, true, 'Clinic/hospital buildings'),
(19, '1112', 'Medical Equipment', NULL, 4, true, 'Diagnostic equipment'),
(19, '1113', 'Furniture', NULL, 4, false, 'Office furniture'),
(19, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(19, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'Operating funds'),
(19, '1220', 'Patient Receivables', NULL, 3, true, 'Medical receivables'),
(19, '1230', 'Inventories', NULL, 3, true, 'Medical supplies'),
(19, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(19, '2100', 'EQUITY', NULL, 2, true, 'Organization equity'),
(19, '2110', 'Capital', NULL, 3, true, 'Initial funding'),
(19, '2120', 'Reserves', NULL, 3, true, 'Accumulated reserves'),
(19, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(19, '2210', 'Loans and Borrowings', NULL, 3, true, 'Facility financing'),
(19, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(19, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(19, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(19, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(19, '3100', 'REVENUE', NULL, 2, true, 'Healthcare revenue'),
(19, '3110', 'Patient Fees', NULL, 3, true, 'Medical services'),
(19, '3120', 'Insurance Claims', NULL, 3, true, 'Medical aid reimbursements'),
(19, '3130', 'Government Funding', NULL, 3, true, 'Healthcare grants'),
(19, '3140', 'Other Income', NULL, 3, false, 'Donations, research'),
(19, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(19, '4100', 'COST OF SALES', NULL, 2, true, 'Medical service costs'),
(19, '4110', 'Medical Supplies', NULL, 3, true, 'Drugs, consumables'),
(19, '4120', 'Laboratory Costs', NULL, 3, true, 'Diagnostic testing'),
(19, '4130', 'Equipment Maintenance', NULL, 3, true, 'Medical equipment service'),
(19, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(19, '4210', 'Employee Costs', NULL, 3, true, 'Medical and admin salaries'),
(19, '4220', 'Depreciation', NULL, 3, true, 'Asset depreciation'),
(19, '4230', 'Insurance', NULL, 3, true, 'Medical malpractice'),
(19, '4240', 'Marketing', NULL, 3, true, 'Patient acquisition'),
(19, '4250', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 19);

-- Arts, Entertainment and Recreation (90-93)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(20, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(20, '1100', 'NON-CURRENT ASSETS', NULL, 2, true, 'Long-term assets'),
(20, '1110', 'Property, Plant and Equipment', NULL, 3, true, 'Entertainment equipment'),
(20, '1111', 'Equipment', NULL, 4, true, 'Sound, lighting systems'),
(20, '1112', 'Vehicles', NULL, 4, false, 'Tour vehicles'),
(20, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(20, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'Operating funds'),
(20, '1220', 'Trade Receivables', NULL, 3, true, 'Ticket/event receivables'),
(20, '1230', 'Inventories', NULL, 3, false, 'Merchandise'),
(20, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(20, '2100', 'EQUITY', NULL, 2, true, 'Organization equity'),
(20, '2110', 'Capital', NULL, 3, true, 'Initial funding'),
(20, '2120', 'Reserves', NULL, 3, true, 'Accumulated reserves'),
(20, '2200', 'NON-CURRENT LIABILITIES', NULL, 2, true, 'Long-term liabilities'),
(20, '2210', 'Loans and Borrowings', NULL, 3, true, 'Equipment financing'),
(20, '2300', 'CURRENT LIABILITIES', NULL, 2, true, 'Short-term liabilities'),
(20, '2310', 'Trade Payables', NULL, 3, true, 'Supplier accounts'),
(20, '2320', 'Tax Liabilities', NULL, 3, true, 'VAT, PAYE, UIF'),
(20, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(20, '3100', 'REVENUE', NULL, 2, true, 'Entertainment revenue'),
(20, '3110', 'Ticket Sales', NULL, 3, true, 'Event tickets'),
(20, '3120', 'Merchandise Sales', NULL, 3, false, 'Souvenirs, merchandise'),
(20, '3130', 'Sponsorships', NULL, 3, false, 'Event sponsorships'),
(20, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(20, '4100', 'COST OF SALES', NULL, 2, true, 'Event production costs'),
(20, '4110', 'Artists/Performers', NULL, 3, true, 'Talent fees'),
(20, '4120', 'Venue Costs', NULL, 3, true, 'Location rental'),
(20, '4130', 'Equipment Rental', NULL, 3, true, 'Sound, lighting rental'),
(20, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(20, '4210', 'Employee Costs', NULL, 3, true, 'Staff salaries'),
(20, '4220', 'Marketing', NULL, 3, true, 'Event promotion'),
(20, '4230', 'Depreciation', NULL, 3, true, 'Equipment depreciation'),
(20, '4240', 'Insurance', NULL, 3, true, 'Event insurance'),
(20, '4250', 'Other Expenses', NULL, 3, false, 'Miscellaneous costs')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 20);

-- Other Service Activities (94-96)
INSERT INTO chart_of_accounts_templates (industry_id, account_code, account_name, account_type_id, level, is_required, description)
VALUES
(21, '1000', 'ASSETS', NULL, 1, true, 'Asset accounts'),
(21, '1200', 'CURRENT ASSETS', NULL, 2, true, 'Short-term assets'),
(21, '1210', 'Cash and Cash Equivalents', NULL, 3, true, 'Organization funds'),
(21, '2000', 'EQUITY AND LIABILITIES', NULL, 1, true, 'Equity and liability accounts'),
(21, '2100', 'EQUITY', NULL, 2, true, 'Organization equity'),
(21, '2110', 'Capital', NULL, 3, true, 'Organization funding'),
(21, '3000', 'INCOME', NULL, 1, true, 'Revenue accounts'),
(21, '3100', 'REVENUE', NULL, 2, true, 'Organization income'),
(21, '3110', 'Grants and Donations', NULL, 3, true, 'Funding received'),
(21, '4000', 'EXPENSES', NULL, 1, true, 'Operating expenses'),
(21, '4200', 'OPERATING EXPENSES', NULL, 2, true, 'Administrative costs'),
(21, '4210', 'Program Costs', NULL, 3, true, 'Organization activities'),
(21, '4220', 'Administrative Costs', NULL, 3, true, 'Management expenses')
WHERE NOT EXISTS (SELECT 1 FROM chart_of_accounts_templates WHERE industry_id = 21);
