/*
 * This source file was generated by the Gradle 'init' task
 * Updated to test the enhanced App class
 */
package fin;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private App appWithoutDb;
    
    @BeforeEach
    void setUp() {
        // Create App instance
        appWithoutDb = new App();
    }
    
    @Test void appHasADefaultGreeting() {
        assertNotNull(appWithoutDb.getGreeting(null), "app should have a default greeting");
        assertTrue(appWithoutDb.getGreeting(null).contains("Hello World"), "default greeting should contain 'Hello World'");
    }
    
    @Test void appHasAPersonalizedGreeting() {
        String name = "John";
        String greeting = appWithoutDb.getGreeting(name);
        assertNotNull(greeting, "app should have a personalized greeting");
        assertTrue(greeting.contains(name), "personalized greeting should contain the name");
    }
}
