name: 🔄 Pull Request Validation

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  pull_request_target:
    branches: [ main ]

env:
  JAVA_VERSION: '17'

jobs:
  # Quick validation for PRs
  pr-validation:
    name: 🚦 PR Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout PR
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: ☕ Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'oracle'
    
    - name: 📋 Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: 🏗️ Build Check
      run: ./gradlew clean compileJava compileTestJava
    
    - name: 🧪 Quick Test Suite
      run: |
        echo "🧪 Running quick test validation..."
        ./gradlew test --tests "fin.AppTest" --tests "fin.ui.OutputFormatterTest"
    
    - name: 📝 Comment PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('PR Validation Results')
          );
          
          const status = '${{ job.status }}' === 'success' ? 'PASSED' : 'FAILED';
          const statusIcon = status === 'PASSED' ? '✅' : '❌';
          
          const body = `🤖 **PR Validation Results**
          
          **Status**: ${statusIcon} ${status}
          **Build**: Completed
          **Quick Tests**: Completed  
          **Commit**: \`${{ github.event.pull_request.head.sha }}\`
          
          ${status === 'PASSED' ? 
            '🎉 Your PR looks good! Ready for full CI/CD pipeline.' : 
            '⚠️ Some issues detected. Please check the logs and fix before merging.'
          }
          
          ---
          *Automated validation • [View Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})*`;

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }
